src/RdpProtector/Models/AccountViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RdpProtector.Models
{
    public class AccountViewModel
    {
        [Required]
        public string SecurityKey { get; set; }
    }
}

src/RdpProtector/Models/ErrorViewModel.cs
using System;

namespace RdpProtector.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/RdpProtector/Models/Setting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RdpProtector.Models
{
    public class Setting
    {
    }
}

src/RdpProtector/Controllers/AccountController.cs
using FormHelper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RdpProtector.Models;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RdpProtector.Controllers
{
    public class AccountController : Controller
    {
        private readonly IConfiguration _config;

        public AccountController(IConfiguration config)
        {
            _config = config;
        }

        public string SecurityKey => _config["SecurityKey"];

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [FormValidator] // http://github.com/sinanbozkus/formhelper
        public async Task<IActionResult> Index(AccountViewModel formData)
        {
            if(SecurityKey == formData.SecurityKey)
            {
                var claimsIdentity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(1))
                };

                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);

                return FormResult.CreateSuccessResult("Please wait...", Url.Action("Index", "Home"));
            }

            return FormResult.CreateErrorResult("Wrong security key!");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index");
        }
    }
}

src/RdpProtector/Controllers/AuditLogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Linq;

namespace RdpProtector.Controllers
{
    [Authorize]
    public class AuditLogController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public IActionResult Index()
        {
            var eventLog = new EventLog("Security");
            var entries = eventLog.Entries
                    .Cast<EventLogEntry>()
                    .Where(x => x.CategoryNumber == 12544)
                    .OrderByDescending(x => x.Index)
                    .Take(100)
                    .ToList();

            return View(entries);
        }
    }
}

src/RdpProtector/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RdpProtector.Models;
using WindowsFirewallHelper;

namespace RdpProtector.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/RdpProtector/Controllers/RuleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;
using WindowsFirewallHelper;

namespace RdpProtector.Controllers
{
    [Authorize]
    public class RuleController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public IActionResult Index()
        {
            var rules = FirewallManager.Instance.Rules.ToList();

            var remotes = rules.Where(x => x.Name.Contains("Remote")).ToList();

            return View(rules);
        }
    }
}

src/RdpProtector/Views/AuditLog/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@using System.Diagnostics
@using System.Collections.Generic

@model List<EventLogEntry>

    <div class="container">
        <div class="card">
            <div class="card-header font-weight-bold">
                Audit Logs (Last 100 Records)
            </div>
            <div class="card-body">
                <table class="table card-table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Date</th>
                            <th>Source</th>
                            <th>EventID</th>
                            <th style="width:150px;">Detail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @switch (item.EntryType)
                                    {
                                        case EventLogEntryType.Error:
                                            <span class="badge p-2 badge-danger">@item.EntryType</span>
                                            break;
                                        case EventLogEntryType.Warning:
                                            <span class="badge p-2 badge-warning">@item.EntryType</span>
                                            break;
                                        case EventLogEntryType.Information:
                                            <span class="badge p-2 badge-info">@item.EntryType</span>
                                            break;
                                        case EventLogEntryType.SuccessAudit:
                                            <span class="badge p-2 badge-success">@item.EntryType</span>
                                            break;
                                        case EventLogEntryType.FailureAudit:
                                            <span class="badge p-2 badge-danger">@item.EntryType</span>
                                            break;
                                        default:
                                            <span class="badge p-2 badge-default">@item.EntryType</span>
                                            break;
                                    }
                                </td>
                                <td>@item.TimeGenerated</td>
                                <td>@item.Source</td>
                                <td>@item.EventID</td>
                                <td><button type="button" class="btn btn-secondary"><i class="fe fe-search"></i> Show</button></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

src/RdpProtector/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/RdpProtector/Views/Rule/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@using System.Diagnostics
@using System.Collections.Generic

@model List<WindowsFirewallHelper.IRule>

    <div class="container">
        <div class="card">
            <div class="card-header font-weight-bold">
                Windows Defender Firewall Rules
            </div>
            <div class="card-body">
                <table class="table card-table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th>A</th>
                            <th>B</th>
                            <th>C</th>
                            <th>D</th>
                            <th style="width:150px;">Detail</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.IsEnable - @item.Name - @item.Scope</td>
                                <td>@item.Protocol</td>
                                <td>@{if(item.LocalPorts.Any()) { @item.LocalPorts[0] }}</td>
                                <td>@{ if(item.RemotePorts.Any()) { @item.RemotePorts[0] }}</td>
                                <td><button type="button" class="btn btn-secondary"><i class="fe fe-search"></i> Show</button></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

src/RdpProtector/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="./favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
    <title>RDP Protector</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <script src="./assets/js/require.min.js"></script>
    <script>
      requirejs.config({
          baseUrl: '.'
      });
    </script>
    <!-- Dashboard Core -->
    <link href="./assets/css/dashboard.css" rel="stylesheet" />
    <script src="./assets/js/dashboard.js"></script>
    <!-- c3.js Charts Plugin -->
    <link href="./assets/plugins/charts-c3/plugin.css" rel="stylesheet" />
    <script src="./assets/plugins/charts-c3/plugin.js"></script>
    <!-- Google Maps Plugin -->
    <link href="./assets/plugins/maps-google/plugin.css" rel="stylesheet" />
    <script src="./assets/plugins/maps-google/plugin.js"></script>
    <!-- Input Mask Plugin -->
    <script src="./assets/plugins/input-mask/plugin.js"></script>
  </head>
  <body class="">
    <div class="page">
      <div class="page-main">
        <div class="header py-4">
          <div class="container">
            <div class="d-flex">
              <a class="header-brand" asp-controller="Home" asp-action="Index">
                <i class="fa fa-lg fa-shield float-left" style="margin-top:8px; margin-right:8px;"></i>RDP Protector
              </a>
              <div class="d-flex order-lg-2 ml-auto">
                <div class="nav-item d-none d-md-flex">
                  <a asp-controller="Account" asp-action="Logout" class="btn btn-secondary"><i class="fe fe-log-out"></i> Logout</a>
                </div>
              </div>
              <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
              </a>
            </div>
          </div>
        </div>
        <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                  <li class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link"><i class="fe fe-grid"></i> Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a asp-controller="AuditLog" asp-action="Index" class="nav-link"><i class="fe fe-menu"></i> Audit Logs</a>
                  </li>
                  <li class="nav-item">
                    <a asp-controller="Rule" asp-action="Index" class="nav-link"><i class="fe fe-shield"></i> Rules</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="my-3 my-md-5">
            @RenderBody()
        </div>
      </div>
      <footer class="footer">
        <div class="container">
          <div class="row align-items-center flex-row-reverse">
            <div class="col-auto ml-lg-auto">
              <div class="row align-items-center">
                <div class="col-auto">
                  <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item"><a href="https://github.com/sinanbozkus/rdp-protector">Documentation</a></li>
                  </ul>
                </div>
                <div class="col-auto">
                  <a href="https://github.com/sinanbozkus/rdp-protector" class="btn btn-outline-primary btn-sm">Source code</a>
                </div>
              </div>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
              Copyright © @DateTime.Now.Year <a href="https://github.com/sinanbozkus/rdp-protector">RDP Protector</a>. Developed by <a href="http://www.sinanbozkus.com" target="_blank">Sinan BOZKUS</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
    @RenderSection("Scripts", required: false)
  </body>
</html>